### model
model_name_or_path: /root/models/Qwen2.5-7B-Instruct
adapter_name_or_path: /root/autodl-tmp/demo3/output/qwen2.5-7b-qlora
template: qwen
finetuning_type: lora

### data
eval_dataset: bc2gm_test
cutoff_len: 1024
max_new_tokens: 512
do_sample: false

### output
output_dir: /root/autodl-tmp/demo3/predict
overwrite_output_dir: true

### eval
per_device_eval_batch_size: 8
predict_with_generate: true
do_predict: true
