### model
model_name_or_path: /root/models/Qwen2.5-7B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_target: all
quantization_bit: 4
quantization_method: bnb

### dataset
dataset: bc2gm_train
eval_dataset: bc2gm_dev
template: qwen
cutoff_len: 1024
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 8

### output
output_dir: /root/autodl-tmp/demo3/output/qwen2.5-7b-qlora
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 5.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
gradient_checkpointing: true

### eval
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 500

### swanlab
use_swanlab: true
swanlab_project: qwen2.5-ner
swanlab_run_name: bc2gm-qlora
swanlab_mode: cloud
save_only_model: true
save_total_limit: 2
